AWS_UTILITIES_BIN=~/GitHub/rkiel/aws-utilities/bin
export PATH=${AWS_UTILITIES_BIN}:$PATH

function get_awssu_commands()
{
  COMPREPLY=(`awssu tab ${COMP_LINE}`)
}

function get_awscc_commands()
{
  COMPREPLY=(`awscc tab ${COMP_LINE}`)
}

function get_awsgenerate_commands()
{
  COMPREPLY=(`awsgenerate tab ${COMP_LINE}`)
}

complete -F get_awssu_commands awssu
complete -F get_awscc_commands awscc
complete -F get_awsgenerate_commands awsgenerate
